### ISSUE TITLE
JS errors preventing content editing or adding

### ISSUE THREAD

**Issue by deanebarker** [episerver/episerver-labs-content-manager-docs#1]
See this video:

https://www.dropbox.com/s/8x7r2cv5njiry4u/content-manager.mp4?dl=0

This is a custom view, configured in code (but the same thing happened from the Dashboard with no custom view). Everything worked great, except that the Edit and Add buttons didn't see to be connected to anything.

* Clicking edit did nothing (note the Network panel on the right -- no network request was generated).
* The Add New bottom blanked the screen out, but again, nothing else happened, and no network traffic was generated.

It did this from the Dashboard too.

There are considerable JS errors in the console...

![content-manager](https://user-images.githubusercontent.com/1533433/80246497-20807e00-8632-11ea-981d-777d55d35c16.jpg)

**Comment by deanebarker** [comment]
We determined this was because I hadn't installed the `Episerver.Labs.GridView` package.

This is technically a bug. Content Manager _should_ run without that. This will be corrected in a future release, but, for now, you need to install the Grid View package as well.

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=EPiServer.Labs.ContentManager&v=0.1.1
