### ISSUE TITLE
Should be possible to define sort order for dashboard views

### ISSUE THREAD

**Issue by tomahg** [episerver/episerver-labs-content-manager-docs#14]
When creating views like the example with:
`public class CarsView : ContentManagerViewConfigurationBase`

It should be possible to set `SortOrder` to control the order of the views/tabs.

**Comment by gregwiechec** [comment]
There is SortOrder field, but because of the bug it was not used properly. It will be fixed.

**Comment by barteksekula** [comment]
Fixed in 0.3.1
