### ISSUE TITLE
Unable to edit child pages from «children grid»

### ISSUE THREAD

**Issue by tomahg** [episerver/episerver-labs-content-manager-docs#15]
Unable to edit child pages from «children grid».

I have full access to the child pages, but a dash is shown instead of the edit-link:
![image](https://user-images.githubusercontent.com/1119118/95023954-582f2f80-0680-11eb-9417-acc4b2fefda1.png)

Markup:
![image](https://user-images.githubusercontent.com/1119118/95023978-814fc000-0680-11eb-8020-1cb5849751c1.png)

**Comment by barteksekula** [comment]
@tomahg what's the master language of those content items?

**Comment by tomahg** [comment]
@barteksekula 

A bit of everything.

- Some only exist in English (English master language)
- Some only exist in Norwegian (Norwegian master language)
- Some exist in both English and Norwegian (some with Norwegian master language, some with English master language)

The problem is the same for all three (four) cases.

**Comment by barteksekula** [comment]
I assume you use WithInlineEdit in your UIDescriptor right?
Unfortunately we only support InlineEdit for Blocks at the moment.
You will have to use WithEdit for pages.

We should definitely clarify the docs around available renderers.

**Comment by tomahg** [comment]
@barteksekula  Ah, I understand.

I was just using the defaults, without specifying the columns with an UIDescriptor.
Adding an UIDescriptor, with `.WithEdit()` - it works. 

Thanks 👍

**Comment by barteksekula** [comment]
But you made a good point @tomahg. Probably we should fallback inline edit to edit based on content type.
I will bring it up tomorrow to the team.

**Comment by tomahg** [comment]
Sounds like a good idea.

Thanks 😄

**Comment by barteksekula** [comment]
It's now fixed in the recent ContentManager version.
We would always fallback to Edit if Quick Edit is not available.
