### ISSUE TITLE
Documentation should be updated

### ISSUE THREAD

**Issue by tomahg** [episerver/episerver-labs-content-manager-docs#18]
Generic type can't be used without type parameter
![image](https://user-images.githubusercontent.com/1119118/95578192-be76d200-0a33-11eb-9a37-a09396755eb3.png)

![image](https://user-images.githubusercontent.com/1119118/95578211-cd5d8480-0a33-11eb-9dca-9ec2942146a0.png)

**Comment by barteksekula** [comment]
@tomahg Can you try SearchContentViewContentData.ViewKey?

**Comment by barteksekula** [comment]
btw. you should not have to set that DefaultView yourself. if you want to replace the default UIDescriptor for content folders you should just register this UIDescriptor in the container like this:
```cs
[UIDescriptorRegistration]
[ServiceConfiguration(typeof(ContentFolderUIDescriptor))]
public class ContentFolderUIEditorDescriptor : ContentFolderUIDescriptor
{ ...  }
```

**Comment by tomahg** [comment]
> @tomahg Can you try SearchContentViewContentData.ViewKey?
Thanks, it worked!

Could you update here?
![image](https://user-images.githubusercontent.com/1119118/95686522-adc68780-0bfe-11eb-8042-5f405d704266.png)

> btw. you should not have to set that DefaultView yourself.
> if you want to replace the default UIDescriptor for content folders you should just register this UIDescriptor in the container like this:
I would like to set DefaultView for list pages. Then I need to set DefaultView, right?

Thanks :-)

**Comment by barteksekula** [comment]
Updated the docs about defaul view & content folders.
https://github.com/episerver/episerver-labs-content-manager-docs/commit/9f6fb596fe8d4869194d511ef2f993ee894c3a33
