### ISSUE TITLE
Should be able to publish new page (enhancement)

### ISSUE THREAD

**Issue by tomahg** [episerver/episerver-labs-content-manager-docs#19]
I find it kind of limiting, only to be able to:
- Create new draft
- Mark as ready for publish

I would like to see the option to publish the content too.

Could be controlled by access rights on the Root page for each implementation of ContentManagerViewConfigurationBase.

**Comment by barteksekula** [comment]
@tomahg is it a duplicate of https://github.com/episerver/episerver-labs-content-manager-docs/issues/5 ?

**Comment by tomahg** [comment]
@barteksekula You are correct.

Sorry about that.

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=EPiServer.Labs.ContentManager&v=0.5.3
