### ISSUE TITLE
Documentation needs implementation examples

### ISSUE THREAD

**Issue by nolmsted** [episerver/episerver-labs-content-manager-docs#2]
This documentation needs examples of how the grid views are configured, including enabling the main grid UI, configuring columns for different content types, and creating custom renderers.

**Comment by oyvindwh** [comment]
Take a look at the issue:8, it maybe help.

**Comment by barteksekula** [comment]
You can find info how to add the Grid View here:
https://github.com/episerver/episerver-labs-content-manager-docs/issues/9#issuecomment-699870900

About configuring columns:
https://github.com/episerver/episerver-labs-content-manager-docs/blob/master/GridView.md#configuring-columns
and renderers:
https://github.com/episerver/episerver-labs-content-manager-docs/blob/master/GridView.md#column-renderers
