### ISSUE TITLE
WithThumbnail doesn't seem working

### ISSUE THREAD

**Issue by vyan024** [episerver/episerver-labs-content-manager-docs#21]
Hi @barteksekula 

I have followed the doc to configure thumbnail or image with the fluent API, but none of them seems working. Below is my content type and structure, can you please advise what do you miss in my code? Thanks
```
Brands
   - Brand (has property named BannerImage)
   - Brand 
   - ......
```

![image](https://user-images.githubusercontent.com/54790930/96388857-760ba100-11f7-11eb-954d-09b8717eb7a1.png)

**Comment by gregwiechec** [comment]
I double checked that it's working locally.

The rendering of the thumbnail is done in gridColumnRenderers.js: thumbnailImage method.
It support default episerver renderers. Maybe you can break in this method and check the renderer URL.

Then compare this URL with the thumnailURL generated for Assets Pane:
![image](https://user-images.githubusercontent.com/12434079/97167682-8687c280-1787-11eb-8a5f-60a32cc1e00f.png)

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=EPiServer.Labs.ContentManager&v=0.3.1
