### ISSUE TITLE
Set Grid View as a default view issue

### ISSUE THREAD

**Issue by vyan024** [episerver/episerver-labs-content-manager-docs#22]
Hi @barteksekula 

I have enabled the grid view as default for my page with the following Grid Settings (see SS 1). However, I notice that when I click on `Edit` link (see SS 2) from child item and go back to parent page, the default view is changed to `OnPage Editing`. 

Can you please advise what do I miss in my configuration? Thanks

![image](https://user-images.githubusercontent.com/54790930/96388857-760ba100-11f7-11eb-954d-09b8717eb7a1.png)

![image](https://user-images.githubusercontent.com/54790930/96389022-be778e80-11f8-11eb-9281-432c01bcd66b.png)

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=EPiServer.Labs.ContentManager&v=0.3.1
