### ISSUE TITLE
Editing draft created new content

### ISSUE THREAD

**Issue by tomahg** [episerver/episerver-labs-content-manager-docs#23]
To reproduce:
- Create new content with Content Manager
- Just "Save" the content, do not "Publish" (as publishing does not work)
- Click the "Edit" button:
![image](https://user-images.githubusercontent.com/1119118/96778213-a156e180-13eb-11eb-9eff-974f275933ea.png)

Result:
The existing content is not edited, new content is created:
![image](https://user-images.githubusercontent.com/1119118/96778263-b3d11b00-13eb-11eb-9862-07bd2954aae2.png)

**Comment by barteksekula** [comment]
I can see a similar issue when trying to create an item without providing required properties.
Is that the case for you?
Could you please try to create an item with no required properties?

**Comment by tomahg** [comment]
I tried again today and was not able to reproduce the issue.
You could be right about the required properties.

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=EPiServer.Labs.ContentManager&v=0.3.1
