### ISSUE TITLE
Images added with drag and drop to XhtmlString properties added to start page's content folder

### ISSUE THREAD

**Issue by tomahg** [episerver/episerver-labs-content-manager-docs#32]
When images are drag-and-dropped from local computer to a XhtmlString-property, the  images are not uploaded to the content folder for the content being edited - but to the content folder for the start page.

**Comment by barteksekula** [comment]
This will be fixed in the next CMS UI & TinyMce release. Will post more details soon.

**Comment by barteksekula** [comment]
Fixed in EPiServer.CMS.UI 11.36.0 & EPiServer.CMS.TinyMce 2.13.5
Both packages needs to be installed.
It will also be fixed in the 1.0.1 version (net5) soon.
