### ISSUE TITLE
Content Manager's pop-up window can't fit XHTML and Long String properties: a horizontal scroll appears

### ISSUE THREAD

**Issue by petriisola** [episerver/episerver-labs-content-manager-docs#33]
The pop-up window is too narrow. Lots of properties generate an annoying horizontal scroll bar.

**Comment by LingSpb** [comment]
Should be fixed in CMS UI Core

**Comment by barteksekula** [comment]
Fixed in https://nuget.optimizely.com/package/?id=EPiServer.Labs.ContentManager&v=1.0.1
