### ISSUE TITLE
How to translate column names in GridView UI for different editors languages

### ISSUE THREAD

**Issue by bsubasic** [episerver/episerver-labs-content-manager-docs#34]
Is there a way for translating column names for different editor's interface languages?

![image](https://user-images.githubusercontent.com/15268114/117809251-3de4b200-b25e-11eb-8b77-6ab30df6cd9b.png)

```
GridSettings = new GridSettings
        {
             Columns = new ColumnsListBuilder()
                    .WithContentName() // <--- **Translate "Content" word** 
                    .WithContentStatus() // <--- **Translate "Status" word**
                    .WithPublishDate()
                    .WithCreatedBy()
                    .WithEdit()
                    .WithPreviewUrl()
                    .Build()
        };
```

**Comment by barteksekula** [comment]
@bsubasic you can do it right now:
`
[UIDescriptorRegistration]
public class NewsListUIEditorDescriptor : ExtendedUIDescriptor<NewsPage>
{
    public NewsListUIEditorDescriptor()
    {
        var localizationService = ServiceLocator.Current.GetInstance<LocalizationService>();
        
        GridSettings = new GridSettings
        {
            Columns = new ColumnsListBuilder()
                .WithThumbnail(nameof(StandardPage.PageImage))
                .WithContentName(localizationService.GetString("/path/to/your/custom/translation"))
                .WithContentStatus()
                .WithCreatedBy()
                .WithPublishDate()
                .WithColumn("IsActive", "Active", "isPageActive", false, ColumnSizeCss.ColumnSize50)
                .WithEdit()
                .WithActionMenu()
                .Build()
        };
    }
}
`
