### ISSUE TITLE
The view style should be specific to the ContentManagerViewConfiguration

### ISSUE THREAD

**Issue by deanebarker** [episerver/episerver-labs-content-manager-docs#6]
If you have multiple views, and you switch to Grid View on one of them, you switch to Grid View on _all_ of them. So the Grid View/Table View option is not specific to views, it's global.

This should be specific to view, not global.

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=EPiServer.Labs.ContentManager&v=0.2.1
