### ISSUE TITLE
Views can have the same Id

### ISSUE THREAD

**Issue by deanebarker** [episerver/episerver-labs-content-manager-docs#7]
You can create two views with the same ID. I don't know if this has further systemic effects, but it does cause both menu options on the overhead bar to be highlight when you're on either of them.

We should probably check this as they initialize, and throw an exception if one of them gets duplicated.

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=EPiServer.Labs.ContentManager&v=0.2.1
